name: tuberculosis_prediction
description: A project that predict tuberculosis disease.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  http: ^0.13.4
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.5
  dropdown_button2: ^1.0.7
  image_picker: ^0.8.4+5
  cached_network_image: ^3.2.0
  webview_flutter: ^3.0.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/noImage.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

